
var LOG_EN = {

  proxyNoCtx:        'proxy: no context',
  proxyFail:         'proxy: {a}',
  proxyPixels:       'proxy: pixel read: {a}',
  proxyEmpty:        'proxy is empty: canvas refused or image fully transparent',
  proxyBlank:        'proxy came out blank: drawing the original',
  proxyNoBuild:      'proxy did not build: {a}',

  oneColLive:        'one colour: live layer: {a}',
  oneColGrey:        'one colour: grey layer: {a}',

  glassDraw:         'glass: drawing failed',
  glassShell:        'glass: shell did not land',
  glassSoft:         'glass: smoothing did not apply',
  glassAbbr:         'glass: aberration did not land',
  frameDraw:         'frame: drawing failed',
  bycDraw:           'by colour: selection did not apply',
  blurDraw:          'blur: image did not draw in window',
  lensBuild:         'loupe: circle did not build',
  lensShow:          'loupe: circle did not land on screen',
  loupeCut:          'cut loupe: window did not draw',
  glassGridImg:      'glass grid: image did not land in sample',
  glassGridByc:      'glass grid: by colour sample did not land',
  glassGridBase:     'glass grid: base did not land in cell',
  glassGridAbbr:     'glass grid: lens sample did not land',

  edit:              'edit: {a}',
  markerTail:        '/marker',
  undoStep:          'step back: stack {a}',
  screen:            'screen: {a}',
  canvasWord:        'canvas',
  gesture:           'gesture: {a}',
  tool:              'tool: {a}',
  release:           'release',
  perfTail:          'draw tail',
  probeField:        'probe, field {a}: {b}',

  clipFallback:      'clipboard, fallback: {a}',
  clip:              'clipboard: {a}',
  easyfixHist:       'easyfix: histogram not taken',
  easyfixLow:        'easyfix: black point not below half at any strength, lo={a}',
  easyfixSoft:       'easyfix: black point not below half, stepped back by strength',
  autoHist:          'auto: histogram not taken',
  autoPoints:        'auto: white point not above black, {a}/{b}',
  maskRead:          'cut: mask pixel did not read',
  eyeRead:           'eyedropper: image pixels did not read',

  sess:              'session store, {a}: {b}',
  sessWrite:         'write {a}',
  sessWriteAbort:    'write {a} aborted',
  sessReadBefore:    'read before write {a}',
  sessRead:          'read',
  sessErase:         'erase',
  sessCopy:          'file copy',
  sessMarkBuild:     'markup build',
  sessMarkParse:     'markup parse',
  sessNoStoreWrite:  'session store, write {a}: store did not open',
  sessNoStoreRead:   'session store, read: store did not open',
  sessNoStoreErase:  'session store, erase: store did not open',
  sessCopyEmpty:     'session store, file copy: shell returned empty',
  sessMarkNotSaved:  'session store: markup not saved',
  sessMarkNoBytes:   'session store: markup present, image bytes missing',
  sessMarkOther:     'session store: markup from another file, not applied',
  sessCopyNotImage:  'session store: copy did not open as image, work lost',
  noReason:          'no reason given',

  openTimeout:       'image did not answer within {a}s: {b}',
  openFail:          'image did not open: {a}',
  openZeroSize:      'zero size received',
  openDecode:        'decode refused',
  liteNoCtx:         'lite: no context',
  liteFail:          'lite: {a}',
  sheetNoCtx:        'blank sheet: no context',
  storeFail:         'store did not open: {a}',

  stkThumb:          'stickers: thumbnail did not build: {a}',
  stkList:           'stickers: list did not read',
  stkListWhy:        'stickers: list did not read: {a}',
  stkPut:            'stickers: not saved',
  stkPutWhy:         'stickers: not saved: {a}',
  stkDel:            'stickers: delete did not go through: {a}',
  stkScale:          'stickers: downscale failed: {a}',
  toPackBuild:       'to stickers: sheet did not build: {a}',
  toPack:            'to stickers: built sheet did not open as image',

  guardNoCtx:        'no context',
  guardZero:         'canvas is zero',
  guardSize:         'canvas has wrong size: {a}',
  guardPixels:       'save guard: pixel read: {a}',
  guardBlank:        'save guard: sheet came out blank where the image lies',
  saveAs:            'save: {a}',
  shareAs:           'share: {a}',
  saveCancel:        'save cancelled: {a}',
  saveFail:          'save failed: {a}',
  handOff:           'file hand-off failed: {a}'
};
